//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.SavedJobs = new HashSet<SavedJob>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Location { get; set; }
        public string Company { get; set; }
        public string Experience { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Education { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Poster { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedJob> SavedJobs { get; set; }
    }
}
